package com.example.quranplayer;

import java.util.Hashtable;
public class Quran {
    public static Hashtable<Integer, Integer> verselookup;

    //I want to have a binary search tree
    //for the collection of verses per Chapter
    //114 Binary Search Trees, Each element will have an mp3 file as well as pointer
    //to the next verse so O(log n) search is only done for finding the first verse
    //I also want a hashtable that maps a chapter number to its known max verses
    public static void fillTable(){
        Hashtable maxVerseLookup = new Hashtable();
        maxVerseLookup.put(1, 7);
        maxVerseLookup.put(2, 286);
        maxVerseLookup.put(3, 200);
        maxVerseLookup.put(4, 176);
        maxVerseLookup.put(5, 120);
        maxVerseLookup.put(6, 165);
        maxVerseLookup.put(7, 206);
        maxVerseLookup.put(8, 75);
        maxVerseLookup.put(9, 129);
        maxVerseLookup.put(10,109);
        maxVerseLookup.put(11,123);
        maxVerseLookup.put(12, 111);
        maxVerseLookup.put(13, 43);
        maxVerseLookup.put(14, 52);
        maxVerseLookup.put(15, 99);
        maxVerseLookup.put(16, 128);
        maxVerseLookup.put(17, 111);
        maxVerseLookup.put(18, 110);
        maxVerseLookup.put(19, 98);
        maxVerseLookup.put(20, 135);
        maxVerseLookup.put(21, 112);
        maxVerseLookup.put(22, 78);
        maxVerseLookup.put(23, 118);
        maxVerseLookup.put(24, 64);
        maxVerseLookup.put(25, 77);
        maxVerseLookup.put(26, 227);
        maxVerseLookup.put(27, 93);
        maxVerseLookup.put(28, 88);
        maxVerseLookup.put(29, 69);
        maxVerseLookup.put(30, 60);
        maxVerseLookup.put(31, 34);
        maxVerseLookup.put(32, 30);
        maxVerseLookup.put(33, 73);
        maxVerseLookup.put(34, 54);
        maxVerseLookup.put(35, 45);
        maxVerseLookup.put(36, 83);
        maxVerseLookup.put(37, 182);
        maxVerseLookup.put(38, 88);
        maxVerseLookup.put(39, 75);
        maxVerseLookup.put(40, 85);
        maxVerseLookup.put(41, 54);
        maxVerseLookup.put(42, 53);
        maxVerseLookup.put(43, 89);
        maxVerseLookup.put(44, 59);
        maxVerseLookup.put(45, 37);
        maxVerseLookup.put(46, 35);
        maxVerseLookup.put(47, 38);
        maxVerseLookup.put(48, 29);
        maxVerseLookup.put(49, 18);
        maxVerseLookup.put(50, 45);
        maxVerseLookup.put(51, 60);
        maxVerseLookup.put(52, 49);
        maxVerseLookup.put(53, 62);
        maxVerseLookup.put(54, 55);
        maxVerseLookup.put(55, 78);
        maxVerseLookup.put(56, 96);
        maxVerseLookup.put(57, 29);
        maxVerseLookup.put(58, 22);
        maxVerseLookup.put(59, 24);
        maxVerseLookup.put(60, 13);
        maxVerseLookup.put(61, 14);
        maxVerseLookup.put(62, 11);
        maxVerseLookup.put(63, 11);
        maxVerseLookup.put(64, 18);
        maxVerseLookup.put(65, 12);
        maxVerseLookup.put(66, 12);
        maxVerseLookup.put(67, 30);
        maxVerseLookup.put(68, 52);
        maxVerseLookup.put(69, 52);
        maxVerseLookup.put(70, 44);
        maxVerseLookup.put(71, 28);
        maxVerseLookup.put(72, 28);
        maxVerseLookup.put(73, 20);
        maxVerseLookup.put(74, 56);
        maxVerseLookup.put(75, 40);
        maxVerseLookup.put(76, 31);
        maxVerseLookup.put(77, 50);
        maxVerseLookup.put(78, 40);
        maxVerseLookup.put(79, 46);
        maxVerseLookup.put(80, 42);
        maxVerseLookup.put(81, 29);
        maxVerseLookup.put(82, 19);
        maxVerseLookup.put(83, 36);
        maxVerseLookup.put(84, 25);
        maxVerseLookup.put(85, 22);
        maxVerseLookup.put(86, 17);
        maxVerseLookup.put(87, 19);
        maxVerseLookup.put(88, 26);
        maxVerseLookup.put(89, 30);
        maxVerseLookup.put(90, 20);
        maxVerseLookup.put(91, 15);
        maxVerseLookup.put(92, 21);
        maxVerseLookup.put(93, 11);
        maxVerseLookup.put(94, 8);
        maxVerseLookup.put(95, 8);
        maxVerseLookup.put(96, 19);
        maxVerseLookup.put(97, 5);
        maxVerseLookup.put(98, 8);
        maxVerseLookup.put(99, 8);
        maxVerseLookup.put(100, 11);
        maxVerseLookup.put(101, 11);
        maxVerseLookup.put(102, 8);
        maxVerseLookup.put(103, 3);
        maxVerseLookup.put(104, 9);
        maxVerseLookup.put(105, 5);
        maxVerseLookup.put(106, 4);
        maxVerseLookup.put(107, 7);
        maxVerseLookup.put(108, 3);
        maxVerseLookup.put(109, 6);
        maxVerseLookup.put(110, 3);
        maxVerseLookup.put(111, 5);
        maxVerseLookup.put(112, 4);
        maxVerseLookup.put(113, 5);
        maxVerseLookup.put(114, 6);
        //instantiates the verselookup table which won't ever change
        verselookup = maxVerseLookup;
    }
}